### ISSUE TITLE
Modificación módulo 'transform_data.py'

### ISSUE THREAD

**Issue by maggiemusa** [DorelyMS/git-ids#3]
Hola Dore,

Dentro del módulo transform_data.py, hay que importar el módulo numpy (import numpy as np), porque sin él no reconoce la función "quitar_acentos".

Saludos

**Comment by DorelyMS** [comment]
Gracias, Maggie!!! Ya Agrego el módulo

**Comment by DorelyMS** [comment]
Se agregó módulo numpy a script
